Models/ViewModels/ManageUserRolesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HotBug.Models.ViewModels
{
    public class ManageUserRolesViewModel
    {
        public HBUser HBUser { get; set; }

        public MultiSelectList Roles { get; set; }

        public List<string> SelectedRoles { get; set; }
    }
}

Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using HotBug.Extensions;
using HotBug.Models;
using HotBug.Models.ViewModels;
using HotBug.Services.Interfaces;

namespace HotBug.Controllers
{
    [Authorize]
    public class UserRolesController : Controller
    {
        private readonly IHBRolesService _rolesService;
        private readonly IHBCompanyInfoService _companyInfoService;

        public UserRolesController(IHBCompanyInfoService companyInfoService,
                                   IHBRolesService rolesService)
        {
            _companyInfoService = companyInfoService;
            _rolesService = rolesService;
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {

            // add an instance of the ViewModel as a list
            List<ManageUserRolesViewModel> model = new();

            // get CompanyId
            int companyId = User.Identity.GetCompanyId()!.Value;

            // get all users in the company
            List<HBUser> users = await _companyInfoService.GetAllMembersAsync(companyId);
            // instantiate ViewModel


            // use _roleService


            // Create multi-selects
            foreach (HBUser user in users)
            {
                ManageUserRolesViewModel viewModel = new();
                viewModel.HBUser = user;
                IEnumerable<string> selected = await _rolesService.GetUserRolesAsync(user);
                viewModel.Roles = new MultiSelectList(await _rolesService.GetRolesAsync(), "Name", "Name", selected);

                model.Add(viewModel);
            }

            // return the model to the view
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {
            // get the company id
            int companyId = User.Identity.GetCompanyId().Value;

            // Instantiate the ITUser
            HBUser hBUser = (await _companyInfoService.GetAllMembersAsync(companyId)).FirstOrDefault(u => u.Id == member.HBUser.Id);

            // Get the roles for the user
            IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(hBUser);


            // Grab the selected roles  
            string userRole = member.SelectedRoles.FirstOrDefault();

            if (!string.IsNullOrEmpty(userRole))
            {
                // Remove the user from the roles
                if (await _rolesService.RemoveUserFromRolesAsync(hBUser, roles))
                {
                    // Add the user to the role
                    await _rolesService.AddUserToRoleAsync(hBUser, userRole);
                }
            }

            // return to the view
            return RedirectToAction(nameof(ManageUserRoles));
        }
    }
}

Views/UserRoles/ManageUserRoles.cshtml
@model IEnumerable<HotBug.Models.ViewModels.ManageUserRolesViewModel>

<!-- Sidebar-right-->
<div class="sidebar sidebar-right sidebar-animate">
    <div class="panel panel-primary card mb-0 box-shadow">
        <div class="tab-menu-heading border-0 p-3">
            <div class="card-title mb-0">Settings</div>
            <div class="card-options ms-auto">
                <a class="sidebar-remove"><i class="fe fe-x"></i></a>
            </div>
        </div>
        <div class="panel-body tabs-menu-body latest-tasks p-0 border-0">
            <div class="tabs-menu ">
                <!-- Tabs -->
                <ul class="nav panel-tabs">
                    <li><a asp-area="Identity" asp-page="/Account/Manage/Index" target="_blank" title="Profile"><i class="fe fe-bell tx-15 me-2"></i>Profile</a></li>
                    <li><a asp-action="Index" asp-controller="Notifications"><i class="fe fe-bell tx-15 me-2"></i> Notifications</a></li>
                </ul>
            </div>
            <div class="tab-content">
            </div>
        </div>
    </div>
</div>

<div class="row mt-4">
    <h2 class="m-t-0 h3"><b>Manage Member Roles </b></h2>
    @foreach (var member in Model)
    {
        <div class="row">
            <div class="card col-4 m-3">
                <div class="card-body">
                    <p class="text-muted font-13 m-b-30">
                        This form displays the current roles assigned to the user: <strong class="text-info">@member.HBUser.FullName</strong>.
                        Use the dropdown to select the roles this user should be assigned.
                        Once roles are selected, click "Assign Roles" to submit the form.
                    </p>
                    <hr />
                    <form asp-action="ManageUserRoles" asp-controller="UserRoles" method=post>
                        <input type="hidden" asp-for="@member.HBUser.Id"/>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="@member.Roles" class="custom-label">
                                        Roles for @member.HBUser.FullName
                                    </label>
                                    <select asp-for="@member.SelectedRoles" class="form-control" asp-items="@member.Roles" multiple>

                                    </select>
                                    <hr />
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Assign Role" class="btn btn-info"/>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }
</div>