Models/ViewModels/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HotBug.Models.ViewModels
{
    public class AssignPMViewModel
    {
        public Project Project { get; set; }
        public SelectList PMList { get; set; }
        public string PMID { get; set; }
    }
}

Controllers/NotificationsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HotBug.Data;
using HotBug.Models;

namespace HotBug.Controllers
{
    public class NotificationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotificationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Notifications
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Notifications.Include(n => n.Recipient).Include(n => n.Sender).Include(n => n.Ticket);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Notifications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notifications == null)
            {
                return NotFound();
            }

            var notification = await _context.Notifications
                .Include(n => n.Recipient)
                .Include(n => n.Sender)
                .Include(n => n.Ticket)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notification == null)
            {
                return NotFound();
            }

            return View(notification);
        }

        // GET: Notifications/Create
        public IActionResult Create()
        {
            ViewData["RecipientId"] = new SelectList(_context.Users, "Id", "FullName");
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "FullName");
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description");
            return View();
        }

        // POST: Notifications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TicketId,Title,Message,Created,RecipientId,SenderId,Viewed")] Notification notification)
        {
            if (ModelState.IsValid)
            {
                _context.Add(notification);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RecipientId"] = new SelectList(_context.Users, "Id", "FullName", notification.RecipientId);
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "FullName", notification.SenderId);
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description", notification.TicketId);
            return View(notification);
        }

        // GET: Notifications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Notifications == null)
            {
                return NotFound();
            }

            var notification = await _context.Notifications.FindAsync(id);
            if (notification == null)
            {
                return NotFound();
            }
            ViewData["RecipientId"] = new SelectList(_context.Users, "Id", "FullName", notification.RecipientId);
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "FullName", notification.SenderId);
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description", notification.TicketId);
            return View(notification);
        }

        // POST: Notifications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TicketId,Title,Message,Created,RecipientId,SenderId,Viewed")] Notification notification)
        {
            if (id != notification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(notification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotificationExists(notification.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RecipientId"] = new SelectList(_context.Users, "Id", "FullName", notification.RecipientId);
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "FullName", notification.SenderId);
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description", notification.TicketId);
            return View(notification);
        }

        // GET: Notifications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notifications == null)
            {
                return NotFound();
            }

            var notification = await _context.Notifications
                .Include(n => n.Recipient)
                .Include(n => n.Sender)
                .Include(n => n.Ticket)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notification == null)
            {
                return NotFound();
            }

            return View(notification);
        }

        // POST: Notifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Notifications == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Notifications'  is null.");
            }
            var notification = await _context.Notifications.FindAsync(id);
            if (notification != null)
            {
                _context.Notifications.Remove(notification);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotificationExists(int id)
        {
            return (_context.Notifications?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }

}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Hosting;
using HotBug.Data;
using HotBug.Extensions;
using HotBug.Models;
using HotBug.Models.Enums;
using HotBug.Models.ViewModels;
using HotBug.Services;
using HotBug.Services.Interfaces;
using HotBug.Controllers;


namespace HotBug.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly UserManager<HBUser> _userManager;
        private readonly IHBProjectService _projectService;
        private readonly IHBLookupService _lookupService;
        private readonly IHBTicketService _ticketService;
        private readonly IHBFileService _fileService;
        private readonly IHBTicketHistoryService _historyService;


        public TicketsController(UserManager<HBUser> userManager,
                                 IHBProjectService projectService,
                                 IHBLookupService lookupService,
                                 IHBTicketService ticketService,
                                 IHBFileService fileService,
                                 IHBTicketHistoryService historyService)
        {
            _userManager = userManager;
            _projectService = projectService;
            _lookupService = lookupService;
            _ticketService = ticketService;
            _fileService = fileService;
            _historyService = historyService;
        }

        // GET: Tickets

        public async Task<IActionResult> MyTickets()
        {
            HBUser itUser = await _userManager.GetUserAsync(User);

            List<Ticket> tickets = await _ticketService.GetTicketsByUserIdAsync(itUser.Id, itUser.CompanyId);

            return View(tickets);
        }

        public async Task<IActionResult> AllTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> tickets = await _ticketService.GetAllTicketsByCompanyAsync(companyId);

            if (User.IsInRole(nameof(Roles.Developer)) || User.IsInRole(nameof(Roles.Submitter)))
            {
                return View(tickets.Where(t => t.Archived == false));
            }
            else
            {
                return View(tickets);
            }
        }

        public async Task<IActionResult> ArchivedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> tickets = await _ticketService.GetArchivedTicketsAsync(companyId);

            return View(tickets);
        }

        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> UnassignedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;
            string itUserId = _userManager.GetUserId(User);

            List<Ticket> tickets = await _ticketService.GetUnassignedTicketsAsync(companyId);

            if (User.IsInRole(nameof(Roles.Admin)))
            {
                return View(tickets);
            }
            else
            {
                List<Ticket> pmTickets = new();
                foreach (Ticket ticket in tickets)
                {
                    if (await _projectService.IsAssignedProjectManagerAsync(itUserId, ticket.ProjectId))
                    {
                        pmTickets.Add(ticket);
                    }
                }

                return View(pmTickets);
            }
        }

        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpGet]
        public async Task<IActionResult> AssignDeveloper(int id)
        {
            AssignDeveloperViewModel model = new();

            model.Ticket = await _ticketService.GetTicketByIdAsync(id);
            model.Developers = new SelectList(await _projectService.GetProjectMembersByRoleAsync(model.Ticket.ProjectId, nameof(Roles.Developer)),
                                              "Id", "FullName");

            return View(model);
        }

        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignDeveloper(AssignDeveloperViewModel model)
        {
            if (model.DeveloperId != null)
            {

                HBUser hBUser = await _userManager.GetUserAsync(User);

                //OLD TICKET
                Ticket oldTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);

                try
                {
                    await _ticketService.AssignTicketAsync(model.Ticket.Id, model.DeveloperId);

                }
                catch (Exception)
                {

                    throw;
                }

                //NEW TICKET
                Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);
                await _historyService.AddHistoryAsync(oldTicket, newTicket, hBUser.Id);

                return RedirectToAction(nameof(Details), new { id = model.Ticket.Id });

            }

            return RedirectToAction(nameof(AssignDeveloper), new { id = model.Ticket.Id });
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ticket ticket = await _ticketService.GetTicketByIdAsync(id.Value);

            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        // async methods must invoke a Task<>!
        public async Task<IActionResult> Create()
        {
            HBUser hBUser = await _userManager.GetUserAsync(User);

            int companyId = User.Identity.GetCompanyId().Value;

            if (User.IsInRole(nameof(Roles.Admin)))
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetAllProjectsByCompanyAsync(companyId), "Id", "Name");
            }
            else
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetUserProjectsAsync(hBUser.Id), "Id", "Name");
            }

            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        //these items bind to the Ticket:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ProjectId,Description,Created,TicketTypeId,TicketPriorityId")] Ticket ticket)
        {
            HBUser hBUser = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {

                try
                {
                    ticket.Created = DateTime.Now;
                    ticket.OwnerUserId = hBUser.Id;

                    ticket.TicketStatusId = (await _ticketService.LookupTicketStatusIdAsync(nameof(HBTicketStatus.New))).Value;

                    await _ticketService.AddNewTicketAsync(ticket);

                    //TODO Ticket History

                    Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(ticket.Id);
                    await _historyService.AddHistoryAsync(null, newTicket, hBUser.Id);


                    //TODO Ticket Notification

                }
                catch (Exception)
                {

                    throw;
                }

                return RedirectToAction(nameof(Create));

            }
            if (User.IsInRole(nameof(Roles.Admin)))
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetAllProjectsByCompanyAsync(hBUser.CompanyId), "Id", "Name");
            }
            else
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetUserProjectsAsync(hBUser.Id), "Id", "Name");
            }

            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name");
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ticket ticket = await _ticketService.GetTicketByIdAsync(id.Value);

            if (ticket == null)
            {
                return NotFound();
            }

            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name", ticket.TicketPriorityId);
            ViewData["TicketStatusId"] = new SelectList(await _lookupService.GetTicketStatusesAsync(), "Id", "Name", ticket.TicketStatusId);
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name", ticket.TicketTypeId);

            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Views/Projects/Details.cshtml
@model HotBug.Models.Project
@using HotBug.Models.Enums
@using HotBug.Services.Interfaces
@using Microsoft.AspNetCore.Identity
@using System.ComponentModel.DataAnnotations;


@inject UserManager<HBUser> UserManager
@inject IHBProjectService ProjectService
@inject IHBTicketHistoryService HistoryService
@inject IHBTicketService TicketService

@{
    ViewData["Title"] = "Details";

    HBUser hBUser = await UserManager.GetUserAsync(User);
    HBUser projectManager = await ProjectService.GetProjectManagerAsync(Model.Id);
}

<!-- Sidebar-right-->
<div class="sidebar sidebar-right sidebar-animate">
    <div class="panel panel-primary card mb-0 box-shadow">
        <div class="tab-menu-heading border-0 p-3">
            <div class="card-title mb-0">Settings</div>
            <div class="card-options ms-auto">
                <a class="sidebar-remove"><i class="fe fe-x"></i></a>
            </div>
        </div>
        <div class="panel-body tabs-menu-body latest-tasks p-0 border-0">
            <div class="tabs-menu ">
                <!-- Tabs -->
                <ul class="nav panel-tabs">
                    <li><a asp-area="Identity" asp-page="/Account/Manage/Index" target="_blank" title="Profile"><i class="fe fe-bell tx-15 me-2"></i>Profile</a></li>
                    <li><a asp-action="Index" asp-controller="Notifications"><i class="fe fe-bell tx-15 me-2"></i> Notifications</a></li>
                </ul>
            </div>
            <div class="tab-content">
            </div>
        </div>
    </div>
</div>

<div>
    <div class="container-fluid">
        <div class="row mt-4">
            <div class="col-12 col-lg-6">
                <!--PROJECT SNAPSHOT-->
                <div class="card p-4" style="overflow-y:auto;height:320px;">
                    <div class="body">
                        @* Project Name *@
                        <h5 class="text-dark"><strong>PROJECT DETAILS</strong></h5>
                        <h5 class="text-dark mt-1">@Model.Name</h5>
                        @* Project Description *@
                        <p class="text-dark mt-1">@Model.Description</p>
                        <div class="progress-container progress-info m-b-25">
                            @*  <span class="progress-badge text-dark" style="font-size:small">Project Status</span> *@
                            @* <div class="progress text-dark mt-2"> *@
                            @* Razor code block *@

                            @{
                                var start = Model.StartDate;
                                var end = Model.EndDate;
                                var today = DateTime.Now;
                                var percent = today >= end ? 100 : today < start ? 0 : Math.Round((today.Subtract(start)) / (end.Subtract(start)) * 100);
                            }

                            <div class="card p-3">
                                <div class="text-dark">
                                    <h5>TEAM DATA</h5>
                                </div>
                                <div class="body text-dark" style="overflow-y:auto;height:60px;">
                                    <ul class="right_chat list-unstyled mb-0">

                                        @* Logic for avatars *@

                                        @foreach (HBUser member in await ProjectService.GetAllProjectMembersExceptPMAsync(Model.Id))
                                        {
                                            <li class="">
                                                <div class="">
                                                    <span class="">@member.FullName</span>
                                                    <span class="" style="font-size:x-small">[@((await UserManager.GetRolesAsync(member)).FirstOrDefault())]</span>
                                                </div>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6">
                <!--PROJECT DATA-->
                <div class="card p-4" style="overflow-y:auto;height:320px;">
                    <div class="body">
                        <h5 class="text-dark"><strong>PROJECT DATA</strong></h5>
                        <ul class=" text-dark">
                            <div class="row">
                            <li class="col-6 mb-1"><strong>Start Date: </strong></li>
                            <li class="col-6 mb-1">@Model.StartDate.ToString(" MMM dd, yyyy")</li>
                            <li class="col-6 mb-1"><strong>Deadline: </strong></li>
                            <li class="col-6 mb-1">@Model.EndDate.ToString(" MMM dd, yyyy")</li>
                            <li class="col-6 mb-1"><strong>Priority: </strong></li>
                            <li class="col-6 mb-1">@Model.ProjectPriority?.Name</li>
                            <li class="col-6 mb-1"><strong>Priority: </strong></li>
                            <li class="col-6 mb-1">@Model.ProjectPriority?.Name</span></li>

                                @if (today < end && today >= start)
                                {
                                <li class="col-6 mb-1"><strong>Status: </strong></li>
                                <li class="col-6 mb-1">Active</li>
                                }
                                else
                                {
                                <li class="col-6 mb-1"><strong>Status: </strong></li>
                                <li class="col-6 mb-1">Inactive</li>
                                }
                    </div>
                    <div class="row">
                        <li class="col-6">
                            <strong>Project Manager: </strong><span class="">
                                        @if (projectManager != null)
                                        {
                            <li class="col-6">@projectManager.FullName</li>

                                            @if (User.IsInRole(nameof(Roles.Admin)) || (hBUser.Id == projectManager.Id))
                                            {
                                <a asp-action="AssignMembers" asp-controller="Projects" asp-route-id="@Model.Id" class="btn btn-xs btn-outline-info mt-5">Manage Team</a>
                                            }
                                        }
                                        else
                                        {
                            <li class="col-6">Not Assigned</li>
                                            @if (User.IsInRole(nameof(Roles.Admin)))
                                            {
                                <span><a asp-action="AssignPM" asp-controller="Projects" asp-route-projectid="@Model.Id" class="btn btn-xs btn-outline-info mt-3">Assign PM</a></span>
                                            }
                                        }
                        </span>
                        </li>

                    </div>

                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-1">

        <div class="col-12 col-md-4 col-lg-3">
            <!--PROJECT ACTIVITY-->
            <div class="card p-4" style="overflow-y:auto;height:480px;">
                <div class="text-dark">
                    <h5><strong>PROJECT ACTIVITY</strong></h5>
                    <hr />
                </div>
                <div class="body text-dark">
                        @* Project Activity loop *@
                        @foreach (TicketHistory history in await HistoryService.GetProjectTicketsHistoriesAsync(Model.Id, hBUser.CompanyId))
                        {
                        <div class="">
                            <span class="">@history.Created.ToString("dd MMM yyyy")</span>
                            <h6>@history.Description</h6>
                            <span>By: <a href="" title="@history.User.FullName">@history.User.FullName</a></span>
                            <div>
                                <p>The ticket <b>@history.Property</b> was edited</p>
                                <p>@($"Previous {history.Property}: {history.OldValue}")</p>
                                <p>@($"Current {history.Property}: {history.NewValue}")</p>
                            </div>
                        </div>
                        }
                </div>
            </div>
        </div>

        <div class="col-12 col-md-8 col-lg-9">
            <!--PROJECT TICKETS-->
            <div class="card p-4" style="overflow-y:auto;height:480px;">
                <div class="text-dark">
                    <h5><strong>PROJECT TICKETS</strong></h5>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-hover text-dark">
                            <thead class="">
                                <tr class="bg-dark text-light">
                                        @* Table header *@
                                    <th class="text-light wd-lg-20p">Title</thj>
                                    <th class="text-light">Developer</th>
                                    <th class="text-light">Status</th>
                                    <th class="text-light">Priority</th>
                                    <th class="text-light">Date</th>
                                    <th class="text-light">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                    @* Table body *@

                                    @foreach (var ticket in Model.Tickets.OrderByDescending(d => d.Created))
                                    {
                                    <tr>
                                        <td><a asp-action="Details" asp-controller="Tickets" asp-route-id="@ticket.Id" style="color:black"><strong>@ticket.Title</strong></a> </td>
                                        <td>
                                                @if (ticket.DeveloperUserId != null)
                                                {
                                                    @ticket.DeveloperUser?.FullName
                                                }
                                                else
                                                {
                                                    if (User.IsInRole(nameof(Roles.Admin)) || User.IsInRole(nameof(Roles.ProjectManager)))
                                                    {
                                                    <a class="btn btn-xs btn-info" asp-action="AssignDeveloper" asp-controller="Tickets" asp-route-id="@ticket.Id">Assign Dev</a>
                                                    }

                                                }
                                        </td>
                                            @if (ticket.TicketStatus.Name == "New")
                                            {
                                            <td><span class="badge-success">@ticket.TicketStatus.Name </span></td>

                                            }
                                            else
                                            {
                                            <td><span class="badge-primary">@ticket.TicketStatus.Name </span></td>
                                            }
                                        <td><span class="badge-warning">@ticket.TicketPriority.Name </span></td>
                                        <td>@ticket.Created.ToString("MM-dd-yyyy")</td>
                                        <td>
                                            <a class="btn btn-sm btn-outline-info" asp-action="Details" asp-controller="Tickets" asp-route-id="@ticket.Id" title="Details"><i class="fs-5 bi-justify"></i></a>
                                                @if (ticket.DeveloperUserId == hBUser.Id || ticket.OwnerUserId == hBUser.Id || (projectManager?.Id == hBUser.Id) || User.IsInRole(nameof(Roles.Admin)))
                                                {
                                                <a class="btn btn-sm btn-outline-secondary" asp-action="Edit" asp-controller="Tickets" asp-route-id="@ticket.Id" title="Edit"><i class="fs-5 bi-pencil"></i></a>
                                                }

                                                @if (User.IsInRole("Admin") || (projectManager?.Id == hBUser.Id))
                                                {
                                                <a class="btn btn-sm btn-outline-danger"><i class="fs-5 bi-archive" title="Archive"></i></a>
                                                }
                                        </td>
                                    </tr>
                                    }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>